// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ietmxyqkixtmurxnvhid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldG14eXFraXh0bXVyeG52aGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTExNjcsImV4cCI6MjA2ODMyNzE2N30._vlB7P0IA6zZ-k6hnMwC-DEzPCsNyfOAd_JHLdb-_5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});